"""Auto-discover an unknown app's UI via menu bar walk.

Opens the app, walks AXMenuBar, extracts menu titles + child items + keyboard
shortcuts, and writes a draft app-skill markdown to app-skills/native/<bundle>.md.
"""
from __future__ import annotations

import os
import time
from pathlib import Path
from typing import Optional

try:
    from ApplicationServices import (
        AXUIElementCreateApplication, AXUIElementCopyAttributeValue,
        kAXChildrenAttribute, kAXTitleAttribute, kAXMenuBarAttribute,
        kAXMenuItemCmdCharAttribute, kAXMenuItemCmdModifiersAttribute,
    )
    from AppKit import NSWorkspace
    HAVE_AX = True
except Exception as _e:
    HAVE_AX = False
    _ERR = repr(_e)


def _attr(elem, name):
    try:
        err, val = AXUIElementCopyAttributeValue(elem, name, None)
        return val if err == 0 else None
    except Exception:
        return None


def _walk_menu(elem, depth=0, out: Optional[list] = None):
    if out is None:
        out = []
    title = _attr(elem, kAXTitleAttribute)
    cmd_char = _attr(elem, kAXMenuItemCmdCharAttribute)
    cmd_mods = _attr(elem, kAXMenuItemCmdModifiersAttribute)
    if title:
        item = {"depth": depth, "title": str(title)}
        if cmd_char:
            mods = []
            if cmd_mods:
                m = int(cmd_mods)
                if m & 0x01: mods.append("shift")
                if m & 0x02: mods.append("opt")
                if m & 0x04: mods.append("ctrl")
                if not (m & 0x08): mods.append("cmd")  # default cmd if not 0x08
            else:
                mods = ["cmd"]
            item["shortcut"] = "+".join(mods + [str(cmd_char)])
        out.append(item)
    children = _attr(elem, kAXChildrenAttribute) or []
    for c in children:
        _walk_menu(c, depth + 1, out)
    return out


def explore(app_name: str, *, write_skill: bool = True,
            settle_s: float = 1.5) -> dict:
    if not HAVE_AX:
        return {"ok": False, "error": _ERR}
    import subprocess
    subprocess.run(["open", "-a", app_name], check=False, timeout=10)
    time.sleep(settle_s)

    # Find PID + bundle id of the launched app
    apps = NSWorkspace.sharedWorkspace().runningApplications()
    target = None
    for a in apps:
        if (a.localizedName() or "").lower() == app_name.lower():
            target = a
            break
    if not target:
        return {"ok": False, "error": f"app not running: {app_name}"}
    pid = int(target.processIdentifier())
    bundle = str(target.bundleIdentifier() or "")

    root = AXUIElementCreateApplication(pid)
    menu_bar = _attr(root, kAXMenuBarAttribute)
    if not menu_bar:
        return {"ok": False, "error": "AXMenuBar not exposed",
                "bundle_id": bundle, "pid": pid}
    items = _walk_menu(menu_bar)
    # Filter out the app menu (Apple symbol) noise
    skip_titles = {"Apple", "About", "Window", "Help", "Edit", "Format", "View"}

    shortcuts = [it for it in items if "shortcut" in it]
    submenus = [it for it in items if it["depth"] == 2 and not it.get("shortcut")]

    # Generate draft skill
    if write_skill and bundle:
        skill_dir = (Path(__file__).resolve().parent.parent / "app-skills" / "native")
        skill_dir.mkdir(parents=True, exist_ok=True)
        skill_path = skill_dir / f"{bundle}.md"
        if not skill_path.exists():
            lines = [
                "---",
                f"bundle_id: {bundle}",
                f"name: {app_name}",
                "auto_generated: true",
                "---",
                "",
                f"# {app_name}",
                "",
                "## Surface",
                "Native macOS app (auto-discovered).",
                "",
                "## Keyboard shortcuts (from menu bar)",
                "",
                "| Action | Shortcut |",
                "| --- | --- |",
            ]
            for s in shortcuts[:50]:
                lines.append(f"| {s['title']} | `{s['shortcut']}` |")
            lines += ["", "## Auto-generated", "",
                      "This file was generated by `argus_app_explore`. ",
                      "Edit and remove `auto_generated: true` once curated."]
            skill_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
        skill_written = str(skill_path)
    else:
        skill_written = None

    return {
        "ok": True, "app": app_name, "bundle_id": bundle, "pid": pid,
        "menu_items": len(items),
        "shortcuts_extracted": len(shortcuts),
        "shortcuts": shortcuts[:30],
        "skill_written": skill_written,
    }
